[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube

; 上传配置
upload_protocol = stlink
debug_tool = stlink

; 编译选项
build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    -DHSE_VALUE=8000000
    -O2
    -g
    -Wall
    ; 只包含你自己的代码路径
    -ICore/Inc
    -IHardware
    -ISources

; 源文件路径
build_src_filter =
    -<*>
    +<../Core/Src/*>
    +<../Hardware/*>

; 监视器配置
monitor_speed = 115200

; 库依赖
lib_deps =
